# Generated by Django 5.1.7 on 2025-03-24 03:17

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Put VectorExtension first to ensure the vector type is available
        VectorExtension(),
        
        # Then create the model that uses the vector type
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('metadata', models.JSONField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=4096)),
            ],
        ),
    ]