# Generated by Django 5.2 on 2025-04-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pathway',
            index=models.Index(fields=['metadata'], name='api_pathway_metadat_86c163_idx'),
        ),
    ]
