# Generated by Django 5.2 on 2025-05-16 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_agno_memory_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='pathways',
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
        migrations.AlterField(
            model_name='userlearnedcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_courses', to='api.course'),
        ),
        migrations.AddIndex(
            model_name='learningpathway',
            index=models.Index(fields=['metadata'], name='api_learnin_metadat_5cc385_idx'),
        ),
    ]
