# Generated by Django 5.2 on 2025-04-18 14:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pathway_api_pathway_metadat_86c163_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
