# Generated by Django 5.2 on 2025-05-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_message_options_remove_course_pathways_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='matching_skill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userlearnedcourse',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursesearch',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
