# Generated by Django 5.2 on 2025-05-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_matching_skill_course_price_and_more'),
        ('api', '0004_userpreference'),
    ]

    operations = [
    ]
